module2-task1 Разбивка компонента «Конструктор пиццы» на мелкие компоненты
htmlacademy-vue/427583-pizza-1 pull request #2
Opened 2021-08-05 20:39 UTC by RomanBykov

2021-08-06 14:02 UTC, Djaler requested changes

2021-08-06 14:02 UTC, Djaler commented on src/frontend/src/common/components/AppDrag.vue
> +    :draggable="true"
нужно иметь возможность отключать draggable (в нашем случае - когда достигнуто максимальное количество ингредиентов)

2021-08-06 14:02 UTC, Djaler commented on src/frontend/src/common/components/RadioButton.vue
> +      selected: false,
вроде как тут false, а потом записывается строка (из checked). Что-то не то

2021-08-06 14:02 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderSauceSelector.vue
> +        :name="'sauce'"
в таких случаях можно вместо `:name="'sauce'"` делать просто `name="sauce"`

2021-08-06 14:02 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +      @click="decrease"
кнопка стилистически отключается, но нужно ещё и физически её отключать (атрибутом disabled)

2021-08-06 14:02 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +      this.updateCount();
можно навесить на count вотчер, чтобы делать updateCount при любом его изменении, а не дергать руками

2021-08-06 14:02 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +      v-model="count"
а ещё возможна ситуация, что сюда руками наберут неподходящее число. Нужно это обработать

2021-08-06 14:02 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +        (item) => item.type !== ingredient.type
по-моему, тут что-то не то происходит. Получается, что при изменении количества любого ингредиента удаляются все другие ингредиенты

2021-08-06 14:02 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    <BuilderPriceCounter />
нужно добавить расчет цены

2021-08-07 18:51 UTC, RomanBykov commented on src/frontend/src/common/components/AppDrag.vue
> +    :draggable="true"
Ой, точно, спасибо большое!

2021-08-07 18:52 UTC, RomanBykov commented on src/frontend/src/common/components/RadioButton.vue
> +      selected: false,
Согласен, поправил🤔

2021-08-07 18:52 UTC, RomanBykov commented on src/frontend/src/modules/builder/components/BuilderSauceSelector.vue
> +        :name="'sauce'"
Спасибо, классный совет, не знал🙂

2021-08-07 18:53 UTC, RomanBykov commented on src/frontend/src/common/components/ItemCounter.vue
> +      @click="decrease"
Точняк, забыл🤦‍♂️

2021-08-07 18:53 UTC, RomanBykov commented on src/frontend/src/common/components/ItemCounter.vue
> +      this.updateCount();
Супер, классная идея, спасибо!

2021-08-07 18:54 UTC, RomanBykov commented on src/frontend/src/common/components/ItemCounter.vue
> +      v-model="count"
Ну и пришлось тут попотеть, спасибо)

2021-08-07 18:56 UTC, RomanBykov commented on src/frontend/src/views/Index.vue
> +        (item) => item.type !== ingredient.type
Не-не, всё хорошо, так и задумано. Я удаляю именно один конкретный ингредиент, чтобы затем записать его новое значение. Другие ингредиенты остаются на месте👌

2021-08-07 18:57 UTC, RomanBykov commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    <BuilderPriceCounter />
Приехали. Я совсем забыл про итоговый счётчик цены. Стыдно, добавил🤦‍♂️

2021-08-07 20:25 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsItem.vue
> +        this.count > IngredientCount.MIN && this.count <= IngredientCount.MAX
должно быть `<` вместо `<=`, по идее

2021-08-07 20:29 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +        (item) => item.type !== ingredient.type
а, действительно, не так прочитал

2021-08-07 20:31 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +    pizza: {
расчет полной цены тоже удобнее было бы сделать computed

2021-08-07 20:32 UTC, Djaler approved these changes
Пару моментов ещё написал, но это мелочи, можно в следующем PR

2021-08-07 20:32 UTC, merged

2021-08-08 10:08 UTC, RomanBykov commented on src/frontend/src/views/Index.vue
> +    pizza: {
Ой, точно, спасибо!